version: 2
jobs:
 build:
   branches:
      only:
        - main

   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run:
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run:
         command: sh ./build.sh build push
